name: Build and Push Fedora Silverblue Container Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Silverblue image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Containerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
          ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}

    - name: Build and push Kinoite image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./KinoiteContainerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/kinoite-and-red:latest
          ghcr.io/${{ github.repository_owner }}/kinoite-and-red:${{ github.sha }}
